# https://github.com/mxcl/PromiseKit/issues/268

platform :ios, '8.0'
use_frameworks!

inhibit_all_warnings!
pod 'PromiseKit/CorePromise'
pod 'PromiseKit/Foundation'
pod 'PromiseKit/SystemConfiguration'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SUPPORTED_PLATFORMS'] = ['appletvos', 'appletvsimulator'];
        end
    end
end
